spring:
    application:
        name: Hierarchy-Cache
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=2000
        username: h2test
        password: h2test
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
    sql:
        init:
            mode: always
    data:
        redis:
            host: localhost
            port: 6379
            timeout: 5000
